# Generated by Django 5.0.6 on 2024-05-12 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('zipcode', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('MH', 'Maharastra'), ('GJ', 'Gujarat'), ('RJ', 'Rajastan'), ('DL', 'Delhi'), ('AN', 'Andhra Pradesh'), ('KA', 'Karnataka'), ('TN', 'Tamilnadu'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('BR', 'Bihar'), ('JH', 'Jharkhand'), ('OR', 'Orissa'), ('CT', 'Chhattisgarh'), ('PB', 'Punjab'), ('HR', 'Haryana'), ('GOA', 'Goa'), ('JK', 'Jammu and Kashmir'), ('HP', 'Himachal Pradesh'), ('AS', 'Assam'), ('TR', 'Tripura'), ('AR', 'Arunachal Pradesh'), ('AP', 'Andaman and Nicobar Islands'), ('TS', 'Telangana'), ('JH', 'Jharkhand'), ('HP', 'Himachal Pradesh'), ('AS', 'Assam')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
